### ISSUE TITLE
Delay between shimmers

### ISSUE THREAD

**Issue by budo76** [maddyb99/shimmer_animation#10]
It would be useful to specify the delay duration between "shimmers": now you can only decide how much the "shimmer effect" takes from start to end, to make it more quick or slow, but there's no way to set the delay before starting a new shimmer.
So for example, imagine that I want to shimmer an item on the screen, every now and then, to bring user attention to a certain UI element. If I set the duration to 1 second the effect is good but really too frequent and anoying for the user. If I set it to 7 seconds this will bring the shimmer to be extremely slow, loosing the real intended effect behaviour.
A separate "shimmersDelay" param would be useful, in order to set the delay between the end of a shimmer and the start of a new one.

**Comment by maddyb99** [comment]
This is a great suggestion, I would really love to roll out this feature as soon as possible!

**Comment by maddyb99** [comment]
The update has been published to [pub.dev](https://pub.dev/packages/shimmer_animation/) 🎉
You can start using this feature by upgrading your dependency to `^0.2.0`
Please keep contributing and suggesting new features 🙌
