### ISSUE TITLE
Failing Widget Tests due to undisposed Timer

### ISSUE THREAD

**Issue by jxstxn1** [maddyb99/shimmer_animation#21]
**Describe the bug**
If you use the Package and make WidgetTests with `pumpAndSettle()` you will receive an Error of an undisposed Timer.
This is caused due to the Future.delayed Method which is used.

**To Reproduce**
1. Use the Package to Create a Loading Card
2. Make a Widget Test to Test if N Objects of type Shimmer() are displayed
3. See failing tests due to an undisposed Timer

**Expected behavior**
I expected that the tests will pass.

**Comment by jxstxn1** [comment]
https://github.com/jxstxn1/Travel-App

Found something to demonstrate it.
Download it and run it.
If you switch fast between this row:
![image](https://user-images.githubusercontent.com/29661951/144091041-ba433977-660d-4f92-b862-d9b309fa3f14.png)

Then it will produce following error:
`[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _ItemState#f1b57(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.d<…>
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: setState() called after dispose(): _ItemState#b375f(lifecycle state: defunct, not mounted)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.`

**Comment by maddyb99** [comment]
Thank you @jxstxn1 for the example. Will look at this later today. 
I was really curious about this! Thanks again!

**Comment by jxstxn1** [comment]
If you was able to reproduce you can maybe create a new release?
