### ISSUE TITLE
Not working in web

### ISSUE THREAD

**Issue by gouravd** [maddyb99/shimmer_animation#7]
════════ Exception caught by scheduler library ═════════════════════════════════
UnimplementedError
═════════════════════════════════

**Comment by maddyb99** [comment]
Could you please post the complete error or the screenshot of the complete error here.
I would look into it soon!

**Comment by maddyb99** [comment]
Could you please confirm if you are facing the same issue with this patch?
@gouravd

**Comment by gouravd** [comment]
Thanks for the update @maddyb99 . 

I tried this on web and found that it works only once.. basically the shimmer effect works only once..here's the log.. hope its helpful


════════ Exception caught by scheduler library ═════════════════════════════════
The following DomException object was thrown during a scheduler callback:
  IndexSizeError: Failed to execute 'addColorStop' on 'CanvasGradient': The provided value (1.00478) is outside the range (0.0, 1.0).

When the exception was thrown, this was the stack
dart:sdk_internal 149477:18                                    createPaintStyle
dart:sdk_internal 135726:39                                    setUpPaint
dart:sdk_internal 134205:40                                    [_setUpPaint]
dart:sdk_internal 134296:24                                    drawPath
dart:sdk_internal 155037:14                                    apply
...
════════════════════════════════════════════════════════════════════════════════

**Comment by maddyb99** [comment]
I have fixed this error in 3429ab6 and I will push it to Pub soon.
Please try cloning this and verify that your issue has been resolved so that we are good to go 🚀
Thanks for bringing up this issue 🙏

**Comment by gouravd** [comment]
Something's odd.. the cloned code is working but 0.0.6 is showing same error

**Comment by maddyb99** [comment]
Try using ^0.0.7
This will work!
